# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_auto_20181116_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'En cours'), (1, 'Validée'), (2, 'Refusée')], default=0, max_length=3, verbose_name='Staut de la demande'),
        ),
    ]
