# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_auto_20181116_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'En cours'), (1, 'Validée'), (2, 'Refusée')], default=0, verbose_name='Staut de la demande'),
        ),
    ]
