# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 14:23
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_auto_20181116_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='acte_engagement',
            field=models.FileField(upload_to='commandes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'doc', 'docx', 'odt'])], verbose_name="Acte d'engagement*"),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date(2018, 11, 30), null=True, verbose_name='Date de la demande'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dpo_cnil',
            field=models.FileField(upload_to='commandes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'doc', 'docx', 'odt'])], verbose_name='DPO CNIL*'),
        ),
        migrations.AlterField(
            model_name='order',
            name='organisation',
            field=models.ForeignKey(default=92, on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.Organisation', verbose_name='Organisation*'),
        ),
    ]
