# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 10:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0005_auto_20181130_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date(2018, 12, 4), null=True, verbose_name='Date de la demande'),
        ),
    ]
