# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-19 08:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0006_auto_20181204_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date(2019, 2, 19), null=True, verbose_name='Date de la demande'),
        ),
    ]
