# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-22 14:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0007_auto_20190219_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='organisation',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date(2019, 3, 22), null=True, verbose_name='Date de la demande'),
        ),
    ]
