# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-27 13:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0008_auto_20190322_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date(2019, 3, 27), null=True, verbose_name='Date de la demande'),
        ),
    ]
