# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 14:13
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Nom')),
                ('short_name', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Nom abrégé')),
                ('url', models.URLField(blank=True, verbose_name='URL publique')),
                ('host', models.CharField(blank=True, max_length=50, verbose_name='Serveur interne')),
                ('sync_in_ldap', models.BooleanField(default=False, verbose_name='Synchronisé dans le LDAP')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Nom')),
                ('code_insee', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Code INSEE')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4171, verbose_name='Territoire')),
                ('sync_in_ldap', models.BooleanField(default=False, verbose_name='Synchronisé dans le LDAP')),
                ('sync_in_ckan', models.BooleanField(default=False, verbose_name='Synchronisé dans CKAN')),
                ('ckan_slug', models.SlugField(max_length=150, unique=True, verbose_name='CKAN ID')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Dénomination')),
                ('code', models.CharField(max_length=3, verbose_name='Code')),
            ],
            options={
                'verbose_name_plural': "Types d'organisations",
                'verbose_name': "Type d'organisation",
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=10, verbose_name='Téléphone')),
                ('role', models.CharField(blank=True, max_length=150, verbose_name='Fonction')),
                ('activation_key', models.CharField(blank=True, max_length=40)),
                ('key_expires', models.DateTimeField(blank=True)),
                ('orga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Organisation', verbose_name="Organisme d'appartenance")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='organisation',
            name='organisation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.OrganisationType', verbose_name="Type d'organisme"),
        ),
        migrations.AddField(
            model_name='organisation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Organisation', verbose_name='Organisation parente'),
        ),
    ]
