# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 15:36
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Nom')),
                ('code_insee', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Code INSEE')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4171, verbose_name='Territoire')),
                ('sync_in_ldap', models.BooleanField(default=False, verbose_name='Synchronisé dans le LDAP')),
                ('sync_in_ckan', models.BooleanField(default=False, verbose_name='Synchronisé dans CKAN')),
                ('ckan_slug', models.SlugField(max_length=150, unique=True, verbose_name='CKAN ID')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('email', models.EmailField(max_length=254, verbose_name="Adresse mail de l'organisation")),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrganisationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Dénomination')),
                ('code', models.CharField(max_length=3, verbose_name='Code')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Téléphone')),
                ('role', models.CharField(blank=True, max_length=150, null=True, verbose_name='Fonction')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PublishRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateField(auto_now_add=True, verbose_name='Date de la demande')),
                ('date_acceptation', models.DateField(blank=True, null=True, verbose_name='Date acceptation')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(blank=True, max_length=40)),
                ('key_expires', models.DateTimeField(blank=True, default=profiles.models.deltatime_2_days, null=True)),
                ('profile_fields', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Champs profile')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
