# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'managed': False, 'verbose_name': 'Jeu de données', 'verbose_name_plural': 'Jeux de données'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name': 'Ressource'},
        ),
    ]
