# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-16 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commune',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='resourceformats',
            name='ckan_view',
            field=models.CharField(blank=True, choices=[(None, 'N/A'), ('text_view', 'text_view'), ('geo_view', 'geo_view'), ('recline_view', 'recline_view'), ('pdf_view', 'pdf_view')], max_length=100, null=True, verbose_name='Vue'),
        ),
    ]
