# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountactions',
            name='user',
        ),
        migrations.AddField(
            model_name='accountactions',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.Profile'),
        ),
        migrations.AlterField(
            model_name='accountactions',
            name='action',
            field=models.CharField(blank=True, choices=[('confirm_mail', "Confirmation de l'email par l'utilisateur"), ('confirm_new_organisation', "Confirmation par un administrateurde la création d'une orga par l'utilisateur"), ('confirm_rattachement', "Rattachement d'un utilisateur à une organsiation par un administrateur"), ('confirm_referent', "Confirmation du rôle de réferent d'une organisationpour un utilisatur par un administrateur"), ('confirm_contrib', "Confirmation du rôle de contributeur d'une organisationpour un utilisatur par un administrateur"), ('reset_password', 'Réinitialisation du mot de passe')], default='confirm_mail', max_length=250, null=True, verbose_name='Action de gestion de profile'),
        ),
    ]
