# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-19 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import idgo_admin.models.resource


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='ftp_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=idgo_admin.models.resource._ftp_file_upload_to, verbose_name='Fichier déposé sur sFTP'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='up_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=idgo_admin.models.resource._up_file_upload_to, verbose_name='Téléverser un ou plusieurs fichiers'),
        ),
    ]
