# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0002_auto_20170725_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountactions',
            name='org_extras',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.Organisation'),
        ),
        migrations.AlterField(
            model_name='accountactions',
            name='action',
            field=models.CharField(blank=True, choices=[('confirm_mail', "Confirmation de l'email par l'utilisateur"), ('confirm_new_organisation', "Confirmation par un administrateurde la création d'une orga par l'utilisateur"), ('confirm_rattachement', "Rattachement d'un utilisateur à une organsiation par un administrateur"), ('confirm_referent', "Confirmation du rôle de réferent d'une organisationpour un utilisatur par un administrateur"), ('confirm_contribution', "Confirmation du rôle de contributeur d'une organisationpour un utilisatur par un administrateur"), ('reset_password', 'Réinitialisation du mot de passe')], default='confirm_mail', max_length=250, null=True, verbose_name='Action de gestion de profile'),
        ),
        migrations.AlterUniqueTogether(
            name='liaisons_contributeurs',
            unique_together=set([('profile', 'organisation')]),
        ),
        migrations.AlterUniqueTogether(
            name='liaisons_referents',
            unique_together=set([('profile', 'organisation')]),
        ),
    ]
