# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-23 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0002_auto_20171016_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.CharField(max_length=1024, verbose_name='Description')),
                ('ckan_slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Ckan_ID')),
            ],
            options={
                'verbose_name': 'Type de donnée',
                'verbose_name_plural': 'Types de données',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.CharField(max_length=1024, verbose_name='Description')),
                ('ckan_slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Ckan_ID')),
            ],
            options={
                'verbose_name': 'Support technique',
                'verbose_name_plural': 'Supports techniques',
            },
        ),
        migrations.AddField(
            model_name='dataset',
            name='data_type',
            field=models.ManyToManyField(to='idgo_admin.DataType', verbose_name='Type de données'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='support',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.Support', verbose_name='Support technique'),
        ),
    ]
