# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-28 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0002_formattype_resource_formats'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.Territory', verbose_name='Territoire de compétence'),
        ),
        migrations.AddField(
            model_name='resource',
            name='format_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.Resource_Formats'),
        ),
    ]
