# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-28 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0003_auto_20170928_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='data_format',
        ),
    ]
