# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-27 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0003_auto_20170726_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='date_creation',
            field=models.DateField(verbose_name='Date de création du jeu de donnée'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='date_modification',
            field=models.DateField(verbose_name='Date de dernière modification du jeu de donnée'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='date_publication',
            field=models.DateField(verbose_name='Date de publication du jeu de donnée'),
        ),
    ]
