# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-26 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0003_auto_20171023_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Administrateur IDGO'),
        ),
    ]
