# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-27 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0004_auto_20170727_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='access',
            new_name='restricted_level',
        ),
        migrations.AddField(
            model_name='resource',
            name='allowed_organisations',
            field=models.ManyToManyField(to='idgo_admin.Organisation', verbose_name='Organisations autorisées'),
        ),
        migrations.AddField(
            model_name='resource',
            name='allowed_users',
            field=models.ManyToManyField(to='idgo_admin.Profile', verbose_name='Utilisateurs autorisés'),
        ),
    ]
