# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-28 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0004_remove_resource_data_format'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormatType',
        ),
    ]
