# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-21 07:34
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0004_auto_20200825_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotedcat',
            name='sync_with',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None, verbose_name='Organisations synchronisées'),
        ),
        migrations.AddField(
            model_name='remotedcatdataset',
            name='remote_organisation',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='Organisation distante'),
        ),
    ]
