# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0005_dataset_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='support',
        ),
        migrations.AddField(
            model_name='dataset',
            name='support_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.Support', verbose_name='Support technique'),
        ),
    ]
