# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-27 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0005_auto_20170727_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Adresse mail de l'organisation"),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_type',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.OrganisationType', verbose_name="Type d'organisme"),
        ),
    ]
