# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-11 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0006_auto_20201021_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='geocover',
            field=models.CharField(blank=True, choices=[(None, 'Calculé automatiquement'), ('regionale', 'Régionale'), ('jurisdiction', 'Territoire de compétence')], default=None, max_length=30, null=True, verbose_name='Couverture géographique'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='jurisdiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='idgo_admin.Jurisdiction', verbose_name='Territoire de compétence'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='restricted_level',
            field=models.CharField(blank=True, choices=[('public', 'Tous les utilisateurs'), ('registered', 'Utilisateurs authentifiés'), ('only_allowed_users', 'Utilisateurs authentifiés avec droits spécifiques'), ('same_organization', 'Utilisateurs de cette organisation uniquement'), ('any_organization', 'Organisations spécifiées'), ('only_idgo_partners', 'Tous les adhérents/partenaires')], default='public', max_length=20, null=True, verbose_name="Restriction d'accès"),
        ),
        migrations.AlterUniqueTogether(
            name='jurisdictioncommune',
            unique_together=set([('jurisdiction', 'commune')]),
        ),
    ]
