# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-28 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0007_resource_format_type_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='format_type',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='format_type_new',
        ),
        migrations.DeleteModel(
            name='Resource_Formats',
        ),
        migrations.DeleteModel(
            name='ResourceFormats',
        ),
    ]
