# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0008_auto_20170728_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='ckan_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Ckan UUID'),
        ),
    ]
