# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0008_auto_20171102_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='iso_topic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Théme ISO'),
        ),
        migrations.AddField(
            model_name='resourceformats',
            name='protocol',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Protocole'),
        ),
    ]
