# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-28 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0008_auto_20170928_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceFormats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=30, unique=True, verbose_name='Format')),
                ('ckan_view', models.CharField(blank=True, choices=[(None, 'N/A'), ('recline_view', 'recline_view'), ('text_view', 'text_view'), ('geo_view', 'geo_view'), ('recline_view', 'recline_view'), ('pdf', 'pdf_view')], max_length=100, null=True, verbose_name='Vue ')),
            ],
        ),
    ]
