# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0009_auto_20170728_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='ckan_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True, verbose_name='Ckan UUID'),
        ),
    ]
