# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0010_auto_20170728_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='date_creation',
            field=models.DateField(blank=True, null=True, verbose_name='Date de création du jeu de données'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='date_modification',
            field=models.DateField(blank=True, null=True, verbose_name='Date de dernière modification du jeu de données'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='date_publication',
            field=models.DateField(blank=True, null=True, verbose_name='Date de publication du jeu de données'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail du producteur de la donnée'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='created_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date de création de la resource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='restricted_level',
            field=models.CharField(blank=True, choices=[('0', 'Tous les utilisateurs'), ('1', 'Utilisateurs authentifiés'), ('2', 'Utilisateurs authentifiés avec droits spécifiques'), ('3', 'Utilisateurs de cette organisations uniquements'), ('4', 'Organisations spécifiées')], default='0', max_length=20, null=True, verbose_name="Restriction d'accès"),
        ),
    ]
