# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0010_auto_20171117_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='iso_topic',
            field=models.CharField(blank=True, choices=[('farming', 'Agriculture'), ('biota', 'Flore et faune'), ('boundaries', 'Limites politiques et administratives'), ('climatologyMeteorologyAtmosphere', 'Climatologie, météorologie'), ('economy', 'Economie'), ('elevation', 'Topographie'), ('environment', 'Ressources et gestion de l’environnement'), ('geoscientificInformation', 'Géosciences'), ('health', 'Santé'), ('imageryBaseMapsEarthCover', 'Carte de référence de la couverture terrestre'), ('intelligenceMilitary', 'Infrastructures militaires'), ('inlandWaters', 'Hydrographie'), ('location', 'Localisant'), ('oceans', 'Océans'), ('planningCadastre', 'Planification et aménagement du territoire'), ('society', 'Société'), ('structure', 'Aménagements urbains'), ('transportation', 'Infrastructures de transport'), ('utilitiesCommunication', 'Réseaux de télécommunication, d’énergie')], max_length=100, null=True, verbose_name='Thème ISO'),
        ),
        migrations.AlterField(
            model_name='liaisonsreferents',
            name='validated_on',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name="Date de validation de l'action"),
        ),
        migrations.AlterField(
            model_name='resourceformats',
            name='protocol',
            field=models.CharField(blank=True, choices=[('OGC:WMS', 'WMS'), ('OGC:WFS', 'WFS'), ('OGC:WCS', 'WCS'), ('OGC:KML', 'KML'), ('WWW:DOWNLOAD-1.0-http--download', 'Fichier à télécharger'), ('WWW:LINK-1.0-http--link', 'Adresse Internet (URL)'), ('DB:POSTGIS', 'Base de données / Table PostGIS')], max_length=100, null=True, verbose_name='Protocole'),
        ),
    ]
