# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0011_auto_20170728_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='allowed_organisations',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='allowed_users',
        ),
    ]
