# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import idgo_admin.models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0011_auto_20171127_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profil utilisateur', 'verbose_name_plural': 'Profils des utilisateurs'},
        ),
        migrations.AlterField(
            model_name='resource',
            name='up_file',
            field=models.FileField(blank=True, null=True, upload_to=idgo_admin.models.resource._up_file_upload_to, verbose_name='Téléverser un ou plusieurs fichiers'),
        ),
    ]
