# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 14:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idgo_admin', '0012_auto_20170728_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationTagged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_tagged', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_tagged', to='idgo_admin.Organisation')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idgo_admin_organisationtagged_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTagged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idgo_admin_usertagged_items', to='taggit.Tag')),
                ('user_tagged', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tagged', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='organisations_allowed',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='idgo_admin.OrganisationTagged', to='taggit.Tag', verbose_name='Organisations autorisées'),
        ),
        migrations.AddField(
            model_name='resource',
            name='users_allowed',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='idgo_admin.UserTagged', to='taggit.Tag', verbose_name='Utilisateurs autorisés'),
        ),
    ]
