# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0013_auto_20171129_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Organisation active'),
        ),
    ]
