# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0013_auto_20170728_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisationtagged',
            old_name='organisation_tagged',
            new_name='content_object',
        ),
        migrations.RenameField(
            model_name='usertagged',
            old_name='user_tagged',
            new_name='content_object',
        ),
    ]
