# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0014_auto_20170728_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationtagged',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='organisationtagged',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='usertagged',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='usertagged',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='organisations_allowed',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='users_allowed',
        ),
        migrations.DeleteModel(
            name='OrganisationTagged',
        ),
        migrations.DeleteModel(
            name='UserTagged',
        ),
    ]
