# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 15:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idgo_admin', '0015_auto_20170728_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='organisations_allowed',
            field=models.ManyToManyField(to='idgo_admin.Organisation', verbose_name='Utilisateurs autorisés'),
        ),
        migrations.AddField(
            model_name='resource',
            name='users_allowed',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs autorisés'),
        ),
    ]
