# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0016_remove_license_license_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picto',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Pictogramme'),
        ),
    ]
