# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0017_auto_20171215_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ckan_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Ckan UUID'),
        ),
    ]
