# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-31 07:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0017_remove_resource_organisations_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='organisations_allowed',
            field=models.ManyToManyField(blank=True, null=True, to='idgo_admin.Organisation', verbose_name='Utilisateurs autorisés'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='users_allowed',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs autorisés'),
        ),
    ]
