# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0018_category_ckan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ckan_slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Ckan slug'),
        ),
    ]
