# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0019_auto_20170731_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='ckan_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Ckan UUID'),
        ),
    ]
