# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0020_auto_20170801_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='ckan_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Ckan UUID'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rattachement_active',
            field=models.BooleanField(default=False, verbose_name="Rattachement profile-organisation d'appartenance validé"),
        ),
    ]
