# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-10 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0021_auto_20170802_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.Organisation', verbose_name="Organisation d'appartenance"),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_type',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.OrganisationType', verbose_name="Type d'organisation"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contributions',
            field=models.ManyToManyField(related_name='profile_contributions', through='idgo_admin.Liaisons_Contributeurs', to='idgo_admin.Organisation', verbose_name="Organisations dont l'utiliateur est contributeur"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.Organisation', verbose_name="Organisation d'appartenance"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='referents',
            field=models.ManyToManyField(related_name='profile_referents', through='idgo_admin.Liaisons_Referents', to='idgo_admin.Organisation', verbose_name="Organisations dont l'utiliateur est réferent"),
        ),
    ]
