# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0021_auto_20171220_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financier',
            options={'ordering': ('name',), 'verbose_name': "Financeur d'une organisation", 'verbose_name_plural': 'Financeurs'},
        ),
        migrations.AlterModelOptions(
            name='organisationtype',
            options={'ordering': ('name',), 'verbose_name': "Type d'organisation", 'verbose_name_plural': "Types d'organisations"},
        ),
        migrations.AlterField(
            model_name='organisationtype',
            name='code',
            field=models.CharField(max_length=250, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='organisationtype',
            name='name',
            field=models.CharField(max_length=250, verbose_name="Type d'organisation"),
        ),
    ]
