# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-25 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0022_auto_20170810_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='geonet_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True, verbose_name='Metadonnées UUID'),
        ),
        migrations.AlterField(
            model_name='accountactions',
            name='action',
            field=models.CharField(blank=True, choices=[('confirm_mail', "Confirmation de l'email par l'utilisateur"), ('confirm_new_organisation', "Confirmation par un administrateur de la création d'une organisation par l'utilisateur"), ('confirm_rattachement', "Rattachement d'un utilisateur à une organsiation par un administrateur"), ('confirm_referent', "Confirmation du rôle de réferent d'une organisation pour un utilisatur par un administrateur"), ('confirm_contribution', "Confirmation du rôle de contributeur d'une organisation pour un utilisatur par un administrateur"), ('reset_password', 'Réinitialisation du mot de passe')], default='confirm_mail', max_length=250, null=True, verbose_name='Action de gestion de profile'),
        ),
    ]
