# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0026_dataset_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.TextField(unique=True, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom du producteur'),
        ),
    ]
