# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0027_auto_20180207_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='support',
            name='ckan_slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Label court'),
        ),
    ]
