# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-12 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0028_auto_20180207_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='ckan_id',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='Identifiant CKAN'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='ckan_slug',
            field=models.SlugField(blank=True, error_messages={'invalid': "Le label court ne peut contenir ni majuscule, ni caractères spéciaux à l'exception le tiret."}, max_length=100, null=True, unique=True, verbose_name='Label court'),
        ),
        migrations.AlterField(
            model_name='liaisonsreferents',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.Organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='liaisonsreferents',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.Profile', verbose_name='Profil'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='ckan_slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='CKAN ID'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='financier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='idgo_admin.Financier', verbose_name='Financeur'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.License', verbose_name='Licence'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.Dataset', verbose_name='Jeu de données'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='format_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.ResourceFormats', verbose_name='Format'),
        ),
    ]
