# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-12 10:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0029_auto_20180212_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(blank=True, null=True, verbose_name='Action')),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Extras')),
                ('state', models.CharField(choices=[('succesful', 'Tâche terminée avec succés'), ('failed', 'Echec de la tâche'), ('running', 'Tâche en cours de traitement')], default='running', max_length=20, verbose_name='Etat de traitement')),
                ('starting', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp de début de traitement')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Timestamp de fin de traitement')),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='sync_frequency',
            field=models.CharField(choices=[('never', 'Jamais'), ('daily', 'Quotidienne'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuelle'), ('quarterly', 'Trimestrielle'), ('customized', 'Période à déterminer')], default='never', max_length=20, verbose_name='Fréquence de synchronisation'),
        ),
        migrations.AddField(
            model_name='resource',
            name='synchronisation',
            field=models.BooleanField(default=False, verbose_name='Synchronisation de données distante. '),
        ),
    ]
