# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-12 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0031_resource_custom_frequency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Tâche de synchronisation'},
        ),
        migrations.AlterField(
            model_name='resource',
            name='custom_frequency',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Nombre de jours entre chaque synchronisations'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='data_type',
            field=models.CharField(choices=[('N/A', 'N/A'), ('data', 'Données'), ('resource', 'Resources')], default='N/A', max_length=10, verbose_name='type de resources'),
        ),
    ]
