# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-13 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0033_auto_20180213_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financier',
            options={'ordering': ('name',), 'verbose_name': "Financeur d'une action", 'verbose_name_plural': 'Financeurs'},
        ),
    ]
