# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0035_auto_20180213_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
    ]
