# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-15 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0036_auto_20180215_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='custom_frequency',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='sync_frequency',
            field=models.CharField(choices=[('never', 'Jamais'), ('daily', 'Quotidienne'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuelle'), ('quarterly', 'Trimestrielle')], default='never', max_length=20, verbose_name='Fréquence de synchronisation'),
        ),
    ]
