# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-15 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0037_auto_20180215_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountactions',
            old_name='org_extras',
            new_name='organisation',
        ),
    ]
