# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0038_auto_20180215_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='ckan_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True, verbose_name='Identifiant CKAN'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='update_freq',
            field=models.CharField(choices=[('asneeded', 'Lorsque nécessaire'), ('never', 'Non planifiée'), ('intermittently', 'Irrégulière'), ('continuously', 'Continue'), ('realtime', 'Temps réel'), ('daily', 'Journalière'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuelle'), ('quarterly', 'Trimestrielle'), ('semiannual', 'Bi-annuelle'), ('annual', 'Annuelle'), ('Unknow', 'Inconnue')], default='never', max_length=30, verbose_name='Fréquence de mise à jour'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='sync_frequency',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('hourly', 'Toutes les heures'), ('daily', 'Quotidienne (tous les jours à minuit)'), ('weekly', 'Hebdomadaire (tous les lundi)'), ('bimonthly ', 'Bimensuelle (1er et 15 de chaque mois)'), ('monthly', 'Mensuelle (1er de chaque mois)'), ('quarterly', 'Trimestrielle (1er des mois de janvier, avril, juillet, octobre)'), ('biannual', 'Semestrielle (1er janvier et 1er juillet)'), ('monthly', 'Mensuelle (1er janvier)')], default='never', max_length=20, null=True, verbose_name='Fréquence de synchronisation'),
        ),
    ]
