# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-26 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0039_auto_20180222_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='sync_frequency',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('daily', 'Quotidienne (tous les jours à minuit)'), ('weekly', 'Hebdomadaire (tous les lundi)'), ('bimonthly ', 'Bimensuelle (1er et 15 de chaque mois)'), ('monthly', 'Mensuelle (1er de chaque mois)'), ('quarterly', 'Trimestrielle (1er des mois de janvier, avril, juillet, octobre)'), ('biannual', 'Semestrielle (1er janvier et 1er juillet)'), ('annual', 'Annuelle (1er janvier)')], default='never', max_length=20, null=True, verbose_name='Fréquence de synchronisation'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='synchronisation',
            field=models.BooleanField(default=False, verbose_name='Synchronisation de données distante'),
        ),
    ]
