# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-27 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0040_auto_20180226_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='broadcast_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail du diffuseur'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='broadcast_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom du diffuseur'),
        ),
    ]
