# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-27 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0041_auto_20180227_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='broadcast_email',
            new_name='broadcaster_email',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='broadcast_name',
            new_name='broadcaster_name',
        ),
    ]
