# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-21 11:17
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0042_auto_20180227_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='datagis_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, editable=False, null=True, size=None, verbose_name='DataGIS Table UUID'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='update_freq',
            field=models.CharField(choices=[('asneeded', 'Lorsque nécessaire'), ('never', 'Non planifiée'), ('intermittently', 'Irrégulière'), ('continuously', 'Continue'), ('realtime', 'Temps réel'), ('daily', 'Journalière'), ('weekly', 'Hebdomadaire'), ('bimonthly', 'Bi-mensuelle'), ('monthly', 'Mensuelle'), ('quarterly', 'Trimestrielle'), ('biannual', 'Bi-annuelle'), ('annual', 'Annuelle'), ('unknow', 'Inconnue')], default='never', max_length=30, verbose_name='Fréquence de mise à jour'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='sync_frequency',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('daily', 'Quotidienne (tous les jours à minuit)'), ('weekly', 'Hebdomadaire (tous les lundi)'), ('bimonthly', 'Bimensuelle (1er et 15 de chaque mois)'), ('monthly', 'Mensuelle (1er de chaque mois)'), ('quarterly', 'Trimestrielle (1er des mois de janvier, avril, juillet, octobre)'), ('biannual', 'Semestrielle (1er janvier et 1er juillet)'), ('annual', 'Annuelle (1er janvier)')], default='never', max_length=20, null=True, verbose_name='Fréquence de synchronisation'),
        ),
    ]
