# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-04 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0043_auto_20180321_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='idgo_admin.Dataset', verbose_name='Jeu de données'),
        ),
    ]
