# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-09 13:29
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0045_auto_20180709_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='data_type',
            field=models.CharField(choices=[('raw', 'Données brutes'), ('annexe', 'Documentation associée'), ('service', 'Service')], default='raw', max_length=10, verbose_name='Type de la ressource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='datagis_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, editable=False, null=True, size=None, verbose_name='DataGIS IDs'),
        ),
    ]
