# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-17 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0047_auto_20180717_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='is_crige_partner',
            field=models.BooleanField(default=False, verbose_name='Organisation partenaire du CRIGE'),
        ),
        migrations.AddField(
            model_name='profile',
            name='crige_membership',
            field=models.BooleanField(default=False, verbose_name='Utilisateur affilié au CRIGE'),
        ),
    ]
