# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-19 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0048_auto_20180717_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='JurisdictionCommune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Territoires de compétence / Communes',
                'verbose_name': 'Territoire de compétence / Commune',
            },
        ),
        migrations.AlterModelOptions(
            name='commune',
            options={'ordering': ['name'], 'verbose_name': 'Commune', 'verbose_name_plural': 'Communes'},
        ),
        migrations.AlterModelOptions(
            name='jurisdiction',
            options={'verbose_name': 'Territoire de compétence', 'verbose_name_plural': 'Territoires de compétence'},
        ),
        migrations.RemoveField(
            model_name='commune',
            name='id',
        ),
        migrations.RemoveField(
            model_name='jurisdiction',
            name='communes',
        ),
        migrations.RemoveField(
            model_name='jurisdiction',
            name='id',
        ),
        migrations.AlterField(
            model_name='commune',
            name='code',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Code INSEE'),
        ),
        migrations.AlterField(
            model_name='jurisdiction',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Code INSEE'),
        ),
        migrations.AddField(
            model_name='jurisdictioncommune',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.Commune', verbose_name='Commune'),
        ),
        migrations.AddField(
            model_name='jurisdictioncommune',
            name='jurisdiction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.Jurisdiction', verbose_name='Territoire de compétence'),
        ),
    ]
