# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-26 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0050_jurisdictioncommune_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Granularity',
            fields=[
                ('slug', models.SlugField(blank=True, max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Slug')),
                ('name', models.TextField(verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Granularité de la couverture territoriale',
                'verbose_name_plural': 'Granularités des couvertures territoriales',
            },
        ),
        migrations.AddField(
            model_name='dataset',
            name='granularity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='idgo_admin.Granularity', verbose_name='Granularité de la couverture territoriale'),
        ),
    ]
