# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-26 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0051_auto_20180726_1512'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='supportedcrs',
            table=None,
        ),
    ]
