# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-28 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0054_auto_20180727_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='geonet_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True, verbose_name='UUID de la métadonnées'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='ogc_services',
            field=models.BooleanField(default=False, verbose_name='Services OGC'),
        ),
    ]
