# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-30 09:54
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idgo_admin', '0055_auto_20180828_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncExtractorTask',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('success', models.NullBooleanField(verbose_name='Succès')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Start')),
                ('stop_date', models.DateTimeField(blank=True, null=True, verbose_name='Stop')),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Details')),
            ],
            options={
                'verbose_name_plural': "Tâches exécutées par l'extracteur de données",
                'verbose_name': "Tâche exécutée par l'extracteur de données",
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('name', models.SlugField(editable=False, primary_key=True, serialize=False, verbose_name='Nom de la couche')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.Resource', verbose_name='Ressource')),
            ],
            options={
                'verbose_name': 'Couche de données',
            },
        ),
        migrations.AddField(
            model_name='asyncextractortask',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.Layer', verbose_name='Layers'),
        ),
        migrations.AddField(
            model_name='asyncextractortask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
