# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-31 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0056_auto_20180830_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asyncextractortask',
            old_name='stop_date',
            new_name='stop_datetime',
        ),
        migrations.RemoveField(
            model_name='asyncextractortask',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='datagis_id',
        ),
        migrations.AddField(
            model_name='asyncextractortask',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start'),
        ),
        migrations.AddField(
            model_name='asyncextractortask',
            name='submission_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Submission'),
        ),
    ]
