# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-06 08:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0057_auto_20180831_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Titre')),
                ('url', models.URLField(verbose_name='URL')),
                ('options', django.contrib.postgres.fields.jsonb.JSONField(default='{}', verbose_name='Options')),
            ],
            options={
                'verbose_name': 'Fond cartographique',
                'verbose_name_plural': 'Fonds cartographiques',
            },
        ),
    ]
