# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-06 12:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0058_basemaps'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractorSupportedFormat',
            fields=[
                ('name', models.SlugField(editable=False, primary_key=True, serialize=False, verbose_name='Nom')),
                ('description', models.TextField(unique=True, verbose_name='Description')),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Détails')),
            ],
            options={
                'verbose_name': "Format pris en charge par le service d'extraction",
                'verbose_name_plural': "Formats pris en charge par le service d'extraction",
            },
        ),
    ]
