# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-06 14:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0059_extractorsupportedformat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemaps',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Options'),
        ),
    ]
