# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-14 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0061_auto_20180913_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='org_phone',
            new_name='phone',
        ),
    ]
