# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-01 13:30
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0063_auto_20180925_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Geometrie'),
        ),
    ]
