# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-04 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0065_auto_20181004_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='CkanHarvesterDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.Dataset')),
            ],
            options={
                'verbose_name_plural': 'Jeux de données moissonnés',
                'verbose_name': 'Jeu de données moissonné',
            },
        ),
        migrations.AlterModelOptions(
            name='ckanharvester',
            options={'verbose_name': 'CkanHarvester', 'verbose_name_plural': 'CkanHarvester'},
        ),
        migrations.AddField(
            model_name='ckanharvesterdataset',
            name='remote_ckan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.CkanHarvester'),
        ),
    ]
