# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-04 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0066_auto_20181004_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ckanharvesterdataset',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ckanharvesterdataset',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
