# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0067_auto_20181004_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.License', verbose_name='Licence'),
        ),
    ]
