# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 08:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idgo_admin', '0068_auto_20181005_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='ckanharvesterdataset',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creates_dataset', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
