# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0070_ckanharvesterdataset_remote_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ckanharvesterdataset',
            name='remote_dataset',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='Ckan UUID'),
        ),
    ]
