# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0071_auto_20181005_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='ckanharvesterdataset',
            name='remote_organisation',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='Organisation distante'),
        ),
        migrations.AlterUniqueTogether(
            name='ckanharvesterdataset',
            unique_together=set([('remote_ckan', 'dataset')]),
        ),
    ]
