# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-10 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0072_auto_20181008_0933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CkanHarvester',
            new_name='RemoteCkan',
        ),
        migrations.RenameModel(
            old_name='CkanHarvesterDataset',
            new_name='RemoteCkanDataset',
        ),
        migrations.AlterModelOptions(
            name='remoteckan',
            options={'verbose_name': 'Catalogue CKAN distant', 'verbose_name_plural': 'Catalogues CKAN distants'},
        ),
    ]
