# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-10 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0073_auto_20181010_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportedcrs',
            name='regex',
            field=models.TextField(blank=True, null=True, verbose_name='Regx'),
        ),
    ]
