# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0075_auto_20181030_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asyncextractortask',
            name='layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.Layer', verbose_name='Layers'),
        ),
    ]
