# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0076_auto_20181105_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asyncextractortask',
            name='layer',
        ),
        migrations.AddField(
            model_name='asyncextractortask',
            name='foreign_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asyncextractortask',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
