# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0077_auto_20181106_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asyncextractortask',
            old_name='foreign_name',
            new_name='foreign_field',
        ),
        migrations.AddField(
            model_name='asyncextractortask',
            name='foreign_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
