# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0078_auto_20181106_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sftp_password',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Mot de passe sFTP'),
        ),
    ]
