# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import idgo_admin.models.resource


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0079_profile_sftp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='ftp_file',
            field=models.FileField(blank=True, null=True, upload_to=idgo_admin.models.resource._ftp_file_upload_to, verbose_name='Fichier déposé sur FTP'),
        ),
    ]
