# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0080_resource_ftp_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceformats',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='resourceformats',
            name='is_gis_format',
            field=models.BooleanField(default=False, verbose_name='Est un format de données SIG'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='geocover',
            field=models.CharField(blank=True, choices=[(None, 'Indéfinie'), ('regionale', 'Régionale'), ('jurisdiction', 'Territoire de compétence')], default=None, max_length=30, null=True, verbose_name='Couverture géographique'),
        ),
    ]
