# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0081_auto_20181126_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceformats',
            name='extension',
            field=models.CharField(max_length=10, verbose_name='Format'),
        ),
    ]
