# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 14:03
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0083_layer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='attached_ckan_resources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, null=True, size=None),
        ),
    ]
