# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0084_layer_attached_ckan_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='granularity',
            name='order',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
