# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 14:23
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0086_extractorsupportedformat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurisdiction',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Geometrie'),
        ),
    ]
