# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 13:28
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0088_layer_bbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='bbox',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4171, verbose_name='Rectangle englobant'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='bbox',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4171, verbose_name='Rectangle englobant'),
        ),
    ]
