# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0089_auto_20181204_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisationtype',
            options={'ordering': ['name'], 'verbose_name': "Type d'organisation", 'verbose_name_plural': "Types d'organisations"},
        ),
        migrations.AlterField(
            model_name='organisationtype',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='organisationtype',
            name='name',
            field=models.TextField(verbose_name="Type d'organisation"),
        ),
    ]
