# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0090_auto_20181207_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationtype',
            name='id',
        ),
        migrations.AlterField(
            model_name='organisationtype',
            name='code',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Code'),
        ),
    ]
