# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0091_auto_20181207_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceformats',
            name='ckan_format',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='type de format CKAN'),
        ),
        migrations.AlterField(
            model_name='resourceformats',
            name='extension',
            field=models.CharField(max_length=10, verbose_name='Extension du fichier'),
        ),
    ]
