# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0092_auto_20181207_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='organisation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='idgo_admin.OrganisationType', verbose_name="Type d'organisation"),
        ),
    ]
