# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 16:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0093_auto_20181207_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='asyncextractortask',
            name='query',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Query'),
        ),
    ]
