# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0094_asyncextractortask_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='update_freq',
            field=models.CharField(choices=[('asneeded', 'Lorsque nécessaire'), ('never', 'Non planifiée'), ('intermittently', 'Irrégulière'), ('continuously', 'Continue'), ('realtime', 'Temps réel'), ('daily', 'Journalière'), ('weekly', 'Hebdomadaire'), ('bimonthly', 'Bi-mensuelle'), ('monthly', 'Mensuelle'), ('quarterly', 'Trimestrielle'), ('semiannual', 'Bi-annuelle'), ('annual', 'Annuelle'), ('unknow', 'Inconnue')], default='never', max_length=30, verbose_name='Fréquence de mise à jour'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='name',
            field=models.SlugField(editable=False, max_length=100, primary_key=True, serialize=False, verbose_name='Nom de la couche'),
        ),
    ]
