# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-13 12:37
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0095_auto_20181211_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4171, verbose_name='Geometrie'),
        ),
        migrations.AlterField(
            model_name='jurisdiction',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4171, verbose_name='Geometrie'),
        ),
    ]
