# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-15 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0096_auto_20181213_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceformats',
            name='ckan_format',
            field=models.CharField(max_length=10, verbose_name='type de format CKAN'),
        ),
        migrations.AlterField(
            model_name='resourceformats',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
