# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-19 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0097_auto_20190115_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.TextField(verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='update_freq',
            field=models.CharField(choices=[('asneeded', 'Lorsque nécessaire'), ('never', 'Non planifiée'), ('intermittently', 'Irrégulière'), ('continuously', 'Continue'), ('realtime', 'Temps réel'), ('daily', 'Journalière'), ('weekly', 'Hebdomadaire'), ('fortnightly', 'Bi-mensuelle'), ('monthly', 'Mensuelle'), ('quarterly', 'Trimestrielle'), ('semiannual', 'Bi-annuelle'), ('annual', 'Annuelle'), ('unknow', 'Inconnue')], default='never', max_length=30, verbose_name='Fréquence de mise à jour'),
        ),
    ]
