# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-25 15:05
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0100_auto_20190225_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='alternate_titles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Alternate titles'),
        ),
        migrations.AlterField(
            model_name='license',
            name='alternate_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None, verbose_name='Alternate URLs'),
        ),
        migrations.AlterField(
            model_name='license',
            name='maintainer',
            field=models.TextField(blank=True, null=True, verbose_name='Maintainer'),
        ),
        migrations.AlterField(
            model_name='license',
            name='od_conformance',
            field=models.CharField(choices=[('approved', 'Approved'), ('not reviewed', 'Not reviewed'), ('rejected', 'Rejected')], default='not reviewed', max_length=30, verbose_name='Open Definition Conformance'),
        ),
        migrations.AlterField(
            model_name='license',
            name='osd_conformance',
            field=models.CharField(choices=[('approved', 'Approved'), ('not reviewed', 'Not reviewed'), ('rejected', 'Rejected')], default='not reviewed', max_length=30, verbose_name='Open Source Definition Conformance'),
        ),
        migrations.AlterField(
            model_name='license',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
