# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-25 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0101_auto_20190225_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='id',
        ),
        migrations.AlterField(
            model_name='license',
            name='slug',
            field=models.SlugField(max_length=100, primary_key=True, serialize=False, verbose_name='Identifier'),
        ),
    ]
