# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-05 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0102_auto_20190225_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='resource',
            name='ckan_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Ckan UUID'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='restricted_level',
            field=models.CharField(blank=True, choices=[('public', 'Tous les utilisateurs'), ('registered', 'Utilisateurs authentifiés'), ('only_allowed_users', 'Utilisateurs authentifiés avec droits spécifiques'), ('same_organization', 'Utilisateurs de cette organisation uniquement'), ('any_organization', 'Organisations spécifiées')], default='public', max_length=20, null=True, verbose_name="Restriction d'accès"),
        ),
    ]
