# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-05 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0104_auto_20190305_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.TextField(verbose_name='Title'),
        ),
    ]
