# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-05 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0105_auto_20190305_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='ckan_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='ckan_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='datatype',
            old_name='ckan_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='ckan_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='support',
            old_name='ckan_slug',
            new_name='slug',
        ),
    ]
