# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-05 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0108_auto_20190305_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='name',
            new_name='legal_name',
        ),
    ]
