# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-05 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0110_auto_20190305_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceformats',
            name='name',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug'),
        ),
    ]
