# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-05 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0111_auto_20190305_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourceformats',
            old_name='name',
            new_name='slug',
        ),
    ]
