# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-05 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0112_auto_20190305_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='geonet_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True, verbose_name='Identifiant de la fiche de métadonnées'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.Organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='slug',
            field=models.SlugField(blank=True, error_messages={'invalid': "Le label court ne peut contenir ni majuscule, ni caractères spéciaux à l'exception le tiret."}, max_length=100, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
