# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-05 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0113_auto_20190305_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liaisonsresources',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='liaisonsresources',
            name='resource',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='liaisonscontributeurs',
            options={'verbose_name': 'Statut de contributeur', 'verbose_name_plural': 'Statuts de contributeur'},
        ),
        migrations.AlterModelOptions(
            name='liaisonsreferents',
            options={'verbose_name': 'Statut de référent', 'verbose_name_plural': 'Statuts de référent'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Tâche de synchronisation', 'verbose_name_plural': 'Tâches de synchronisation'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='resources',
        ),
        migrations.AlterField(
            model_name='accountactions',
            name='closed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AlterField(
            model_name='accountactions',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='accountactions',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Clé'),
        ),
        migrations.AlterField(
            model_name='accountactions',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.Organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='basemaps',
            name='name',
            field=models.TextField(unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='category',
            name='ckan_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Identifiant CKAN'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='liaisonscontributeurs',
            name='created_on',
            field=models.DateField(auto_now_add=True, verbose_name='Date de la demande de statut de contributeur'),
        ),
        migrations.AlterField(
            model_name='liaisonscontributeurs',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.Organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='liaisonscontributeurs',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.Profile', verbose_name='Profil utilisateur'),
        ),
        migrations.AlterField(
            model_name='liaisonscontributeurs',
            name='validated_on',
            field=models.DateField(blank=True, null=True, verbose_name='Date de la confirmation par un administrateur'),
        ),
        migrations.AlterField(
            model_name='liaisonsreferents',
            name='created_on',
            field=models.DateField(auto_now_add=True, verbose_name='Date de la demande de statut de référent'),
        ),
        migrations.AlterField(
            model_name='liaisonsreferents',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.Profile', verbose_name='Profil utilisateur'),
        ),
        migrations.AlterField(
            model_name='liaisonsreferents',
            name='validated_on',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date de la confirmation par un administrateur'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Administrateur métier'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='membership',
            field=models.BooleanField(default=False, verbose_name='Utilisateur rattaché à une organisation'),
        ),
        migrations.AlterField(
            model_name='support',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse e-mail'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin du traitement'),
        ),
        migrations.AlterField(
            model_name='task',
            name='starting',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Début du traitement'),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('succesful', 'Tâche terminée avec succés'), ('failed', 'Echec de la tâche'), ('running', 'Tâche en cours de traitement')], default='running', max_length=20, verbose_name='État'),
        ),
        migrations.DeleteModel(
            name='LiaisonsResources',
        ),
    ]
