# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-06 12:51
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0114_auto_20190305_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commune',
            options={'ordering': ('code',), 'verbose_name': 'Commune', 'verbose_name_plural': 'Communes'},
        ),
        migrations.AlterModelOptions(
            name='layer',
            options={'verbose_name': 'Couche de données', 'verbose_name_plural': 'Couches de données'},
        ),
        migrations.AlterModelOptions(
            name='mail',
            options={'verbose_name': 'E-mail', 'verbose_name_plural': 'E-mails'},
        ),
        migrations.RemoveField(
            model_name='layer',
            name='attached_ckan_resources',
        ),
        migrations.AlterField(
            model_name='asyncextractortask',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asyncextractortask',
            name='query',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asyncextractortask',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asyncextractortask',
            name='stop_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asyncextractortask',
            name='submission_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asyncextractortask',
            name='success',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='asyncextractortask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asyncextractortask',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='ckan_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Identifiant CKAN'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4171, verbose_name='Géometrie'),
        ),
        migrations.AlterField(
            model_name='extractorsupportedformat',
            name='type',
            field=models.CharField(blank=True, choices=[('raster', 'raster'), ('vector', 'vector')], max_length=6, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='jurisdiction',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4171, verbose_name='Géometrie'),
        ),
        migrations.AlterField(
            model_name='jurisdictioncommune',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creates_jurisdiction', to='idgo_admin.Profile', verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='jurisdictioncommune',
            name='created_on',
            field=models.DateField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='type',
            field=models.CharField(blank=True, choices=[('raster', 'raster'), ('vector', 'vector')], max_length=6, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='license',
            name='alternate_titles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Autres titres'),
        ),
        migrations.AlterField(
            model_name='license',
            name='alternate_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None, verbose_name='Autres URLs'),
        ),
        migrations.AlterField(
            model_name='license',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='license',
            name='title',
            field=models.TextField(verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='supportedcrs',
            name='auth_code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Authority Code'),
        ),
        migrations.AlterField(
            model_name='supportedcrs',
            name='auth_name',
            field=models.CharField(db_index=True, default='EPSG', max_length=100, verbose_name='Authority Name'),
        ),
    ]
