# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-06 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('idgo_admin', '0115_auto_20190306_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
            ],
            options={
                'indexes': [],
                'verbose_name_plural': 'Mots clés',
                'verbose_name': 'Mot clé',
                'proxy': True,
            },
            bases=('taggit.tag',),
        ),
        migrations.AlterField(
            model_name='resourceformats',
            name='protocol',
            field=models.CharField(blank=True, choices=[('OGC:WMS', 'WMS'), ('OGC:WFS', 'WFS'), ('WWW:DOWNLOAD-1.0-http--download', 'ZIP')], max_length=100, null=True, verbose_name='Protocole'),
        ),
    ]
