# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-11 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0116_auto_20190306_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keywords',
            options={'verbose_name': 'Mot-clé', 'verbose_name_plural': 'Mots-clés'},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ('slug',), 'verbose_name': 'Organisation', 'verbose_name_plural': 'Organisations'},
        ),
        migrations.AlterModelOptions(
            name='organisationtype',
            options={'ordering': ('name',), 'verbose_name': "Type d'organisation", 'verbose_name_plural': "Types d'organisations"},
        ),
        migrations.AlterField(
            model_name='dataset',
            name='broadcaster_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse e-mail du diffuseur'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='categories',
            field=models.ManyToManyField(blank=True, to='idgo_admin.Category', verbose_name='Catégories'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse e-mail du producteur'),
        ),
        migrations.AlterField(
            model_name='remoteckandataset',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='remoteckandataset',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Mis-à-jour le'),
        ),
        migrations.AlterField(
            model_name='resourceformats',
            name='protocol',
            field=models.CharField(blank=True, choices=[('OGC:WMS', 'WMS'), ('OGC:WFS', 'WFS'), ('OGC:WCS', 'WCS'), ('OGC:KML', 'KML'), ('WWW:DOWNLOAD-1.0-http--download', 'Fichier à télécharger'), ('WWW:LINK-1.0-http--link', 'Adresse Internet (URL)'), ('DB:POSTGIS', 'Base de données / Table PostGIS')], max_length=100, null=True, verbose_name='Protocole'),
        ),
    ]
