# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-14 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0118_auto_20190311_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceformats',
            name='mimetype',
            field=models.TextField(blank=True, null=True, verbose_name='Type MIME'),
        ),
    ]
