# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-14 09:36
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0119_resourceformats_mimetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceformats',
            name='mimetype',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Type MIME'),
        ),
    ]
