# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-14 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0120_auto_20190314_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='format_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.ResourceFormats', verbose_name='Format'),
        ),
    ]
