# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-15 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0121_auto_20190314_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remoteckandataset',
            old_name='remote_ckan',
            new_name='remote_instance',
        ),
        migrations.AlterUniqueTogether(
            name='remoteckandataset',
            unique_together=set([('remote_instance', 'dataset')]),
        ),
    ]
