# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-19 08:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idgo_admin', '0123_remove_dataset_is_inspire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gdpr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'émission")),
            ],
            options={
                'verbose_name': "Modalités et conditions d'utilisation (RGPD)",
            },
        ),
        migrations.CreateModel(
            name='GdprUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated_on', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date de validation')),
                ('gdpr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.Gdpr', verbose_name='RGPD')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'RGPD / Utilisateur',
            },
        ),
        migrations.AlterUniqueTogether(
            name='gdpruser',
            unique_together=set([('user', 'gdpr')]),
        ),
    ]
