# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-27 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0125_auto_20190319_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountactions',
            name='action',
            field=models.CharField(blank=True, choices=[('confirm_mail', "Confirmation de l'e-mail par l'utilisateur"), ('confirm_new_organisation', "Confirmation par un administrateur de la création d'une organisation par l'utilisateur"), ('confirm_rattachement', "Rattachement d'un utilisateur à une organisation par un administrateur"), ('confirm_referent', "Confirmation du rôle de réferent d'une organisation pour un utilisateur par un administrateur"), ('confirm_contribution', "Confirmation du rôle de contributeur d'une organisation pour un utilisateur par un administrateur"), ('reset_password', 'Réinitialisation du mot de passe'), ('set_password_admin', 'Initialisation du mot de passe suite à une inscription par un administrateur'), ('created_organisation_through_api', "Création d'une organisation depuis l'API")], default='confirm_mail', max_length=250, null=True, verbose_name='Action de gestion de profile'),
        ),
        migrations.AlterField(
            model_name='resourceformats',
            name='protocol',
            field=models.CharField(blank=True, choices=[('OGC:WMS', 'WMS'), ('OGC:WFS', 'WFS'), ('OGC:WCS', 'WCS'), ('OGC:KML', 'KML'), ('WWW:DOWNLOAD-1.0-http--download', 'Fichier à télécharger'), ('WWW:LINK-1.0-http--link', 'Adresse Internet (URL)'), ('DB:POSTGIS', 'Base de données / Table PostGIS')], max_length=100, null=True, verbose_name='Protocole'),
        ),
    ]
