# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-22 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0126_auto_20190327_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True, verbose_name='Slug')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.Category')),
                ('remote_ckan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.RemoteCkan')),
            ],
            options={
                'verbose_name': 'Mapping categorie',
                'verbose_name_plural': 'Mapping categories',
            },
        ),
        migrations.CreateModel(
            name='MappingLicence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True, verbose_name='Slug')),
                ('licence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.License')),
                ('remote_ckan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.RemoteCkan')),
            ],
            options={
                'verbose_name': 'Mapping license',
                'verbose_name_plural': 'Mapping licenses',
            },
        ),
    ]
