# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-26 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0128_task_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='sync_frequency',
            field=models.CharField(blank=True, choices=[('1hour', 'Toutes les heures'), ('3hours', 'Toutes les trois heures'), ('6hours', 'Toutes les six heures'), ('daily', 'Quotidienne (tous les jours à minuit)'), ('weekly', 'Hebdomadaire (tous les lundi)'), ('bimonthly', 'Bimensuelle (1er et 15 de chaque mois)'), ('monthly', 'Mensuelle (1er de chaque mois)'), ('quarterly', 'Trimestrielle (1er des mois de janvier, avril, juillet, octobre)'), ('biannual', 'Semestrielle (1er janvier et 1er juillet)'), ('annual', 'Annuelle (1er janvier)'), ('never', 'Jamais'), ('5mn', 'Toutes les 5 minutes'), ('15mn', 'Toutes les 15 minutes'), ('20mn', 'Toutes les 20 minutes'), ('30mn', 'Toutes les 30 minutes')], default='never', max_length=20, null=True, verbose_name='Fréquence de synchronisation'),
        ),
    ]
