# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-29 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0129_auto_20190426_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remotecsw',
            name='sync_with',
        ),
        migrations.AddField(
            model_name='remotecsw',
            name='getrecords',
            field=models.TextField(blank=True, null=True, verbose_name='Filtre à appliquer au GetRecord'),
        ),
    ]
