# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-29 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0130_auto_20190429_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotecswdataset',
            name='remote_dataset',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True, verbose_name='Jeu de données distant'),
        ),
    ]
