# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-29 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0131_auto_20190429_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remoteckandataset',
            name='remote_organisation',
        ),
    ]
