# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-03 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0133_auto_20190430_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remotecswdataset',
            name='remote_organisation',
        ),
        migrations.AddField(
            model_name='remoteckandataset',
            name='remote_organisation',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='Organisation distante'),
        ),
    ]
