# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-16 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0134_auto_20190503_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='geonet_id',
            field=models.TextField(blank=True, db_index=True, null=True, unique=True, verbose_name='Identifiant de la fiche de métadonnées'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='geonet_id',
            field=models.TextField(blank=True, db_index=True, null=True, unique=True, verbose_name='UUID de la métadonnées'),
        ),
    ]
