# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-22 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0135_auto_20190516_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Site internet'),
        ),
    ]
