# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-18 13:14
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_admin', '0136_auto_20190522_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='alternate_titles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Autres titres'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='update_frequency',
            field=models.CharField(choices=[('asneeded', 'Lorsque nécessaire'), ('never', 'Non planifiée'), ('intermittently', 'Irrégulière'), ('continuously', 'Continue'), ('realtime', 'Temps réel'), ('daily', 'Journalière'), ('weekly', 'Hebdomadaire'), ('fortnightly', 'Bi-mensuelle'), ('monthly', 'Mensuelle'), ('quarterly', 'Trimestrielle'), ('semiannual', 'Bi-annuelle'), ('annual', 'Annuelle'), ('unknown', 'Inconnue')], default='never', max_length=30, verbose_name='Fréquence de mise à jour'),
        ),
    ]
