# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-27 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ihmsettings',
            options={'ordering': ('name',), 'verbose_name': 'champs IHM', 'verbose_name_plural': 'Éditions des IHM'},
        ),
        migrations.AlterField(
            model_name='ihmsettings',
            name='target',
            field=models.CharField(blank=True, choices=[('ckan', 'Ckan'), ('admin', 'Admin')], default='ckan', max_length=100, null=True, verbose_name='Cible'),
        ),
    ]
