# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-06 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihm', '0002_auto_20190327_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ihmsettings',
            options={'ordering': ('name',), 'verbose_name': 'Configuration particulière des IHM', 'verbose_name_plural': 'Configurations particulières des IHM'},
        ),
        migrations.AddField(
            model_name='ihmsettings',
            name='activate',
            field=models.BooleanField(default=False, verbose_name='Activer'),
        ),
    ]
